LOCAL_PATH := $(call my-dir)

# GMessaging
include $(CLEAR_VARS)
LOCAL_MODULE := GMessaging
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := GMessaging.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_OVERRIDES_PACKAGES := Home Launcher2 Launcher3 Launcher3QuickStep NexusLauncherRelease
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
LOCAL_PRODUCT_MODULE := true
include $(BUILD_PREBUILT)
